var $header = $('header');
var $h1 = $('h1');
var $main = $('main');
var $h2 = $('h2');
var $mainList = $('mainList');
var $img = $('img');
var $firstList = $('main li:first-child');
var $lastList = $('main li:last-child');
var $dl = $('dl');
var $dt = $('dt');

$header.addClass('masthead');
$h1.removeClass('big-heading').addClass('logo');
$main.addClass('wrapper')('main p:first-child');
$h2.addClass('slug-head');
$mainList.addClass('slug-list');
$img.addClass('slug.img');
$firstList.addClass('slug-list-first');
$lastList.addClass('slug-list-last');
$dl.addClass('classification');
$dt.removeClass('big-label');
$lastList.show();
